#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_FILE="${ROOT_DIR}/frontend/src/App.tsx"

require_pattern() {
  local description="$1"
  local pattern="$2"
  if ! rg -n --fixed-strings "${pattern}" "${APP_FILE}" >/dev/null; then
    echo "[draft-guard] missing ${description}: ${pattern}"
    exit 1
  fi
}

echo "[draft-guard] checking workspace draft persistence guards"

require_pattern "pending flush callback" "const flushPendingWorkspaceDraft = useCallback((expectedScopeKey?: string) => {"
require_pattern "pending retry timer ref" "const pendingWorkspaceRetryTimerRef = useRef<number | null>(null);"
require_pattern "pending retry delay ref" "const pendingWorkspaceRetryDelayMsRef = useRef(1500);"
require_pattern "pending retry count ref" "const pendingWorkspaceRetryCountRef = useRef(0);"
require_pattern "runtime status ref" "const workspaceDraftRuntimeStatusRef = useRef<WorkspaceDraftRuntimeStatus>({"
require_pattern "pending snapshot write" "writeWorkspaceDraftSnapshot(pending.scopeKey, pending.snapshot);"
require_pattern "pending write result guard" "if (!writeResult.persisted) {"
require_pattern "runtime status flush attempt" "reason: \"flush_attempt\""
require_pattern "pending retry schedule" "pendingWorkspaceRetryTimerRef.current = window.setTimeout(() => {"
require_pattern "pending retry flush call" "flushPendingWorkspaceDraft(pending.scopeKey);"
require_pattern "pending retry delay capture with cap mode" "const retryDelayMs = pendingWorkspaceRetryCountRef.current >= 6"
require_pattern "pending retry fixed interval after cap" "? 12000"
require_pattern "pending retry delay backoff" "pendingWorkspaceRetryDelayMsRef.current = Math.min(retryDelayMs * 2, 12000);"
require_pattern "pending retry count guard before increment" "if (pendingWorkspaceRetryCountRef.current < 6) {"
require_pattern "pending retry count increment" "pendingWorkspaceRetryCountRef.current += 1;"
require_pattern "runtime status persist failed scheduled" "reason: \"persist_failed_retry_scheduled\""
require_pattern "runtime status persist failed waiting" "reason: \"persist_failed_retry_waiting\""
require_pattern "pending clear after persisted" "pendingWorkspaceDraftRef.current = null;"
require_pattern "runtime status persisted" "reason: \"persisted\""
require_pattern "pending retry clear on success" "window.clearTimeout(pendingWorkspaceRetryTimerRef.current);"
require_pattern "pending retry delay reset on success" "pendingWorkspaceRetryDelayMsRef.current = 1500;"
require_pattern "pending retry count reset on success" "pendingWorkspaceRetryCountRef.current = 0;"
require_pattern "legacy cleanup after modern availability" "if (writeResult.canCleanupLegacy && !legacyDraftCleanupDoneRef.current) {"
require_pattern "legacy cleanup verify assignment" "legacyDraftCleanupDoneRef.current = clearLegacyDraftKeysAndVerify().persisted;"
require_pattern "modern store existence check" "function hasModernWorkspaceDraftStore(): boolean {"
require_pattern "modern store parse check" "const parsedStore = parseWorkspaceDraftStore(rawStore);"
require_pattern "modern store schema check" "if (!Number.isFinite(version) || version < 1 || !isRecord(rawStore.entries)) {"
require_pattern "modern store migrated check" "if (parsedStore.migrated) {"
require_pattern "modern store empty entries check" "return Object.keys(rawStore.entries).length === 0;"
require_pattern "scope switch flush" "flushPendingWorkspaceDraft(previousScopeKey);"
require_pattern "pagehide flush listener" "window.addEventListener(\"pagehide\", handlePageHide);"
require_pattern "pagehide cleanup listener" "window.removeEventListener(\"pagehide\", handlePageHide);"
require_pattern "visibilitychange flush listener" "document.addEventListener(\"visibilitychange\", handleVisibilityChange);"
require_pattern "visibilitychange cleanup listener" "document.removeEventListener(\"visibilitychange\", handleVisibilityChange);"
require_pattern "beforeunload flush listener" "window.addEventListener(\"beforeunload\", handleBeforeUnload);"
require_pattern "beforeunload cleanup listener" "window.removeEventListener(\"beforeunload\", handleBeforeUnload);"
require_pattern "window blur flush listener" "window.addEventListener(\"blur\", handleWindowBlur);"
require_pattern "window blur cleanup listener" "window.removeEventListener(\"blur\", handleWindowBlur);"
require_pattern "draft sync hotkey listener" "window.addEventListener(\"keydown\", handleDraftSyncHotkey);"
require_pattern "draft sync hotkey cleanup" "window.removeEventListener(\"keydown\", handleDraftSyncHotkey);"
require_pattern "draft sync hotkey repeat guard" "if (event.repeat) {"
require_pattern "draft sync hotkey key match" "if (!(event.metaKey || event.ctrlKey) || event.key.toLowerCase() !== \"s\") {"
require_pattern "draft sync hotkey shift force flag" "const forceSync = event.shiftKey;"
require_pattern "draft sync hotkey force gate" "if (!forceSync && !workspaceDraftRuntimeCanForceSync(workspaceDraftRuntimeStatusRef.current)) {"
require_pattern "draft sync hotkey flush" "triggerWorkspaceDraftSync(forceSync);"
require_pattern "pending retry cleanup effect" "if (pendingWorkspaceRetryTimerRef.current !== null) {"
require_pattern "pending retry clear on draft update" "window.clearTimeout(pendingWorkspaceRetryTimerRef.current);"
require_pattern "pending retry delay reset on draft update" "pendingWorkspaceRetryDelayMsRef.current = 1500;"
require_pattern "pending retry count reset on draft update" "pendingWorkspaceRetryCountRef.current = 0;"
require_pattern "runtime status draft updated" "reason: \"draft_updated_debounce\""
require_pattern "unmount flush" "flushPendingWorkspaceDraft(draftScopeKey);"
require_pattern "schema version constant" "const WORKSPACE_DRAFT_STORE_SCHEMA_VERSION = 1;"
require_pattern "schema serialize" "__schema_version: WORKSPACE_DRAFT_STORE_SCHEMA_VERSION,"
require_pattern "scope key normalizer" "function normalizeWorkspaceDraftScopeKey(value: string): string | null {"
require_pattern "timeframe alias map" "const LEGACY_TIMEFRAME_ALIASES: Record<string, string> = {"
require_pattern "store merge logic" "const entries = mergeWorkspaceDraftEntries(modernStore.entries, legacyStore.entries);"
require_pattern "persist result gating" "const persistResult = persistWorkspaceDraftStore(trimWorkspaceDraftStore(entries, MAX_WORKSPACE_DRAFTS));"
require_pattern "persist write verify helper" "function setWorkspaceDraftStoreAndVerify(payload: string): WorkspaceDraftPersistResult {"
require_pattern "persist write verify readback" "const verified = strictLocalStorageGetItem(\"workspaceDrafts\");"
require_pattern "legacy cleanup after persist success" "if (persistResult.persisted) {"
require_pattern "clear modern draft store helper" "function clearWorkspaceDraftStoreAndVerify(): WorkspaceDraftPersistResult {"
require_pattern "clear modern draft store call" "const modernCleared = clearWorkspaceDraftStoreAndVerify();"
require_pattern "clear modern draft store decision" "persisted: modernCleared.persisted,"
require_pattern "clear modern draft store failure path" "persistenceTarget: modernCleared.persisted ? \"modern\" : \"none\""
require_pattern "write result type" "type WorkspaceDraftWriteResult = {"
require_pattern "write result field persisted" "persisted: boolean;"
require_pattern "write result field wroteModern" "wroteModern: boolean;"
require_pattern "write result field canCleanupLegacy" "canCleanupLegacy: boolean;"
require_pattern "write result field persistence target" "persistenceTarget: \"modern\" | \"legacy\" | \"none\";"
require_pattern "write result field error kind" "errorKind: WorkspaceDraftPersistErrorKind;"
require_pattern "persist error kind type" "type WorkspaceDraftPersistErrorKind = \"none\" | \"storage_unavailable\" | \"write_failed\" | \"verify_mismatch\";"
require_pattern "persist result type" "type WorkspaceDraftPersistResult = {"
require_pattern "runtime status error kind field" "lastErrorKind: WorkspaceDraftPersistErrorKind | null;"
require_pattern "runtime status error reset on flush attempt" "lastErrorKind: \"none\","
require_pattern "runtime status error assignment on failure" "lastErrorKind: writeResult.errorKind,"
require_pattern "runtime error label helper" "function workspaceDraftPersistErrorKindLabel(value: WorkspaceDraftRuntimeStatus[\"lastErrorKind\"]): string {"
require_pattern "runtime detail includes failure type" "失败类型：\${error}"
require_pattern "persist store returns typed result" "function persistWorkspaceDraftStore(store: Record<string, WorkspaceDraftEntry>): WorkspaceDraftPersistResult {"
require_pattern "set store returns typed result" "function setWorkspaceDraftStoreAndVerify(payload: string): WorkspaceDraftPersistResult {"
require_pattern "legacy persist returns typed result" "function persistLegacyWorkspaceDraftSnapshot(snapshot: WorkspaceDraftSnapshot): WorkspaceDraftPersistResult {"
require_pattern "legacy verify returns typed result" "function verifyLegacyWorkspaceDraftSnapshot(snapshot: WorkspaceDraftSnapshot, title: string): WorkspaceDraftPersistResult {"
require_pattern "legacy clear returns typed result" "function clearLegacyDraftKeysAndVerify(): WorkspaceDraftPersistResult {"
require_pattern "modern clear returns typed result" "function clearWorkspaceDraftStoreAndVerify(): WorkspaceDraftPersistResult {"
require_pattern "legacy fallback write error branch" "return { persisted: false, errorKind: canReadLocalStorage() ? \"write_failed\" : \"storage_unavailable\" };"
require_pattern "legacy fallback verify returns result" "return verifyLegacyWorkspaceDraftSnapshot(snapshot, title);"
require_pattern "legacy fallback call" "const fallbackResult = persistLegacyWorkspaceDraftSnapshot(normalizedSnapshot);"
require_pattern "empty snapshot persist failure without legacy clear" "errorKind: persistResult.errorKind,"
require_pattern "unchanged snapshot modern cleanup decision" "persistenceTarget: hasModernWorkspaceDraftStore() ? \"modern\" : \"legacy\","
require_pattern "modern write success cleanup decision" "return { persisted: true, wroteModern: true, canCleanupLegacy: true, persistenceTarget: \"modern\", errorKind: \"none\" };"
require_pattern "empty snapshot legacy clear fallback helper" "const legacyCleared = clearLegacyDraftKeysAndVerify();"
require_pattern "empty snapshot legacy clear success guard" "if (legacyCleared.persisted) {"
require_pattern "empty snapshot legacy clear success decision" "return { persisted: true, wroteModern: false, canCleanupLegacy: false, persistenceTarget: \"legacy\", errorKind: \"none\" };"
require_pattern "empty snapshot persist failure decision" "errorKind: legacyCleared.errorKind,"
require_pattern "fallback write cleanup decision" "persisted: fallbackResult.persisted,"
require_pattern "legacy clear verify helper" "function clearLegacyDraftKeysAndVerify(): WorkspaceDraftPersistResult {"
require_pattern "legacy clear localstorage read guard" "if (!canReadLocalStorage()) {"
require_pattern "modern store clear localstorage read guard" "function clearWorkspaceDraftStoreAndVerify(): WorkspaceDraftPersistResult {"
require_pattern "localstorage read probe helper" "function canReadLocalStorage(): boolean {"
require_pattern "strict localstorage read helper" "function strictLocalStorageGetItem(key: string): string | null | undefined {"
require_pattern "runtime status publish helper" "function publishWorkspaceDraftRuntimeStatus("
require_pattern "runtime status window bridge" "__aetherWorkspaceDraftRuntime"
require_pattern "runtime status persistence target field" "lastPersistenceTarget: \"modern\" | \"legacy\" | \"none\";"
require_pattern "runtime status persisted target assignment" "lastPersistenceTarget: writeResult.persistenceTarget,"
require_pattern "runtime target label helper" "function workspaceDraftPersistenceTargetLabel(value: WorkspaceDraftRuntimeStatus[\"lastPersistenceTarget\"]): string {"
require_pattern "runtime detail hotkey hint" "Shift + Ctrl/Cmd + S 强制同步"
require_pattern "runtime force sync helper" "function workspaceDraftRuntimeCanForceSync(status: WorkspaceDraftRuntimeStatus): boolean {"
require_pattern "review panel force sync check" "const canForceSyncDraft = workspaceDraftRuntimeCanForceSync(draftRuntime);"
require_pattern "review panel force sync action" "onClick={() => triggerWorkspaceDraftSync()}"
require_pattern "manual draft sync callback" "const triggerWorkspaceDraftSync = useCallback((forceSync = false) => {"
require_pattern "manual draft sync in-flight guard" "if (!forceSync && workspaceDraftRuntimeIsSyncing(workspaceDraftRuntimeStatusRef.current)) {"
require_pattern "manual draft sync pending fallback flush" "if (draftScopeKeyLoaded !== draftScopeKey) {"
require_pattern "manual draft sync pending fallback action" "flushPendingWorkspaceDraft();"
require_pattern "manual draft sync status" "reason: \"draft_manual_sync\""
require_pattern "runtime syncing helper" "function workspaceDraftRuntimeIsSyncing(status: WorkspaceDraftRuntimeStatus): boolean {"
require_pattern "review panel force sync label" "立即同步草稿"
require_pattern "legacy fallback read" "readWorkspaceDraftSnapshot(draftScopeKey, useLegacyFallback);"
require_pattern "modern draft store key" "readJsonStorageByKeys(\"workspaceDrafts\")"
require_pattern "legacy draft store key" "readJsonStorageByKeys(\"workspace_drafts\")"

echo "[draft-guard] passed"
