#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

require_pattern() {
  local description="$1"
  local pattern="$2"
  local file="$3"
  if ! rg -n --fixed-strings "${pattern}" "${file}" >/dev/null; then
    echo "[limit-pct-guard] missing ${description}: ${pattern} (${file})"
    exit 1
  fi
}

echo "[limit-pct-guard] checking limit_pct integration guards"

require_pattern "backend query param" "limit_pct: float = Query(default=10.0, ge=0.1, le=30.0)" "${ROOT_DIR}/backend/app/main.py"
require_pattern "analysis finite-limit guard" "math.isfinite(limit_pct)" "${ROOT_DIR}/backend/app/analysis.py"
require_pattern "analysis non-finite fallback" "else 10.0" "${ROOT_DIR}/backend/app/analysis.py"
require_pattern "analysis limit rule echo" "\"limit_rule\": f\"prev_close_{normalized_limit_pct:g}pct\"" "${ROOT_DIR}/backend/app/analysis.py"
require_pattern "frontend option field" "limitPct: number;" "${ROOT_DIR}/frontend/src/api.ts"
require_pattern "frontend request param" "params.set(\"limit_pct\", String(options.limitPct));" "${ROOT_DIR}/frontend/src/api.ts"
require_pattern "app option clamp" "limitPct: clampNumber(Number(limitPct), 0.1, 30, 10)," "${ROOT_DIR}/frontend/src/App.tsx"
require_pattern "api test NaN limit reject" "limit_pct=NaN" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test nan limit reject" "limit_pct=nan" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test spaced NaN limit reject" "limit_pct=%20NaN%20" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test spaced nan limit reject" "limit_pct=%20nan%20" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test Infinity limit reject" "limit_pct=Infinity" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test inf limit reject" "limit_pct=inf" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test +Infinity limit reject" "limit_pct=%2BInfinity" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test +inf limit reject" "limit_pct=%2Binf" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test spaced Infinity limit reject" "limit_pct=%20Infinity%20" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test spaced inf limit reject" "limit_pct=%20inf%20" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test spaced +Infinity limit reject" "limit_pct=%20%2BInfinity%20" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test spaced +inf limit reject" "limit_pct=%20%2Binf%20" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test -Infinity limit reject" "limit_pct=-Infinity" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test -inf limit reject" "limit_pct=-inf" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test spaced -Infinity limit reject" "limit_pct=%20-Infinity%20" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test spaced -inf limit reject" "limit_pct=%20-inf%20" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test overflow positive limit reject" "limit_pct=1e309" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test overflow positive plus limit reject" "limit_pct=%2B1e309" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test overflow positive spaced limit reject" "limit_pct=%201e309%20" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test overflow positive plus spaced limit reject" "limit_pct=%20%2B1e309%20" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test overflow negative limit reject" "limit_pct=-1e309" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test overflow negative spaced limit reject" "limit_pct=%20-1e309%20" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific too-small reject" "limit_pct=9e-2" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific too-large reject" "limit_pct=3.01e1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific plus too-small reject" "limit_pct=%2B9e-2" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific plus too-large reject" "limit_pct=%2B3.01e1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific negative too-small spaced reject" "limit_pct=%20-9e-2%20" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific negative too-large spaced reject" "limit_pct=%20-3.01e1%20" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific notation limit" "limit_pct=1e1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific notation rule" "assert scientific_limit_payload[\"params\"][\"limit_rule\"] == \"prev_close_10pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific notation upper limit" "limit_pct=1E1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific notation upper rule" "assert scientific_limit_upper_payload[\"params\"][\"limit_rule\"] == \"prev_close_10pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific notation plus limit" "limit_pct=%2B1e1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific notation plus rule" "assert unconstrained_scientific_plus_limit_payload[\"params\"][\"limit_rule\"] == \"prev_close_10pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific notation plus upper limit" "limit_pct=%2B1E1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific notation plus upper rule" "assert unconstrained_scientific_plus_upper_limit_payload[\"params\"][\"limit_rule\"] == \"prev_close_10pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific notation plus upper spaced limit" "limit_pct=%20%2B1E1%20" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific notation plus upper spaced rule" "assert unconstrained_scientific_plus_upper_spaced_limit_payload[\"params\"][\"limit_rule\"] == \"prev_close_10pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test decimal plus limit" "limit_pct=%2B12.5" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test decimal plus rule" "assert unconstrained_decimal_plus_limit_payload[\"params\"][\"limit_rule\"] == \"prev_close_12.5pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test decimal plus spaced limit" "limit_pct=%20%2B12.5%20" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test decimal plus spaced rule" "assert unconstrained_decimal_plus_spaced_limit_payload[\"params\"][\"limit_rule\"] == \"prev_close_12.5pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test min plus limit" "limit_pct=%2B0.1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test min plus rule" "assert plus_min_limit_payload[\"params\"][\"limit_rule\"] == \"prev_close_0.1pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test unconstrained scientific notation limit" "apply_limit_constraints=false&limit_pct=1e1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test unconstrained scientific notation rule" "assert unconstrained_scientific_limit_payload[\"params\"][\"limit_rule\"] == \"prev_close_10pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test unconstrained scientific notation upper limit" "apply_limit_constraints=false&limit_pct=1E1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test unconstrained scientific notation upper rule" "assert unconstrained_scientific_upper_limit_payload[\"params\"][\"limit_rule\"] == \"prev_close_10pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific min limit" "limit_pct=1e-1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific min rule" "assert scientific_min_limit_payload[\"params\"][\"limit_rule\"] == \"prev_close_0.1pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific plus min limit" "limit_pct=%2B1e-1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific plus min rule" "assert scientific_plus_min_limit_payload[\"params\"][\"limit_rule\"] == \"prev_close_0.1pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific max limit" "limit_pct=3e1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific max rule" "assert scientific_max_limit_payload[\"params\"][\"limit_rule\"] == \"prev_close_30pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific plus max limit" "limit_pct=%2B3e1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "api test scientific plus max rule" "assert scientific_plus_max_limit_payload[\"params\"][\"limit_rule\"] == \"prev_close_30pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave unconstrained scientific notation limit" "strategy=wave_zigzag_reversal&threshold_pct=8&apply_limit_constraints=false&limit_pct=1e1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave unconstrained scientific notation upper limit" "strategy=wave_zigzag_reversal&threshold_pct=8&apply_limit_constraints=false&limit_pct=1E1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave unconstrained scientific notation plus limit" "strategy=wave_zigzag_reversal&threshold_pct=8&apply_limit_constraints=false&limit_pct=%2B1e1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave unconstrained scientific notation plus upper limit" "strategy=wave_zigzag_reversal&threshold_pct=8&apply_limit_constraints=false&limit_pct=%2B1E1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave unconstrained scientific notation plus upper spaced limit" "strategy=wave_zigzag_reversal&threshold_pct=8&apply_limit_constraints=false&limit_pct=%20%2B1E1%20" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave unconstrained scientific notation plus spaced limit" "strategy=wave_zigzag_reversal&threshold_pct=8&apply_limit_constraints=false&limit_pct=%20%2B1e1%20" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave unconstrained scientific notation plus min limit" "strategy=wave_zigzag_reversal&threshold_pct=8&apply_limit_constraints=false&limit_pct=%2B1e-1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave constrained scientific notation limit" "strategy=wave_zigzag_reversal&threshold_pct=8&apply_limit_constraints=true&limit_pct=1e1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave constrained scientific notation upper limit" "strategy=wave_zigzag_reversal&threshold_pct=8&apply_limit_constraints=true&limit_pct=1E1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave constrained scientific notation plus limit" "strategy=wave_zigzag_reversal&threshold_pct=8&apply_limit_constraints=true&limit_pct=%2B1e1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave constrained scientific notation plus upper limit" "strategy=wave_zigzag_reversal&threshold_pct=8&apply_limit_constraints=true&limit_pct=%2B1E1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave constrained scientific notation plus upper spaced limit" "strategy=wave_zigzag_reversal&threshold_pct=8&apply_limit_constraints=true&limit_pct=%20%2B1E1%20" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave constrained scientific notation plus spaced limit" "strategy=wave_zigzag_reversal&threshold_pct=8&apply_limit_constraints=true&limit_pct=%20%2B1e1%20" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave constrained scientific notation plus max limit" "strategy=wave_zigzag_reversal&threshold_pct=8&apply_limit_constraints=true&limit_pct=%2B3e1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave unconstrained decimal plus limit" "strategy=wave_zigzag_reversal&threshold_pct=8&apply_limit_constraints=false&limit_pct=%2B12.5" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave constrained min plus limit" "strategy=wave_zigzag_reversal&threshold_pct=8&apply_limit_constraints=true&limit_pct=%2B0.1" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave scientific notation unconstrained rule" "assert unconstrained_scientific_payload[\"params\"][\"limit_rule\"] == \"prev_close_10pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave scientific notation constrained rule" "assert constrained_scientific_payload[\"params\"][\"limit_rule\"] == \"prev_close_10pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave scientific notation constrained plus rule" "assert constrained_scientific_plus_payload[\"params\"][\"limit_rule\"] == \"prev_close_10pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave scientific notation constrained plus upper rule" "assert constrained_scientific_plus_upper_payload[\"params\"][\"limit_rule\"] == \"prev_close_10pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave scientific notation constrained plus upper spaced rule" "assert constrained_scientific_plus_upper_spaced_payload[\"params\"][\"limit_rule\"] == \"prev_close_10pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave scientific notation constrained plus spaced rule" "assert constrained_scientific_plus_spaced_payload[\"params\"][\"limit_rule\"] == \"prev_close_10pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave scientific notation unconstrained plus rule" "assert unconstrained_scientific_plus_payload[\"params\"][\"limit_rule\"] == \"prev_close_10pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave scientific notation unconstrained plus upper rule" "assert unconstrained_scientific_plus_upper_payload[\"params\"][\"limit_rule\"] == \"prev_close_10pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave scientific notation unconstrained plus upper spaced rule" "assert unconstrained_scientific_plus_upper_spaced_payload[\"params\"][\"limit_rule\"] == \"prev_close_10pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave scientific notation unconstrained plus spaced rule" "assert unconstrained_scientific_plus_spaced_payload[\"params\"][\"limit_rule\"] == \"prev_close_10pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave scientific notation unconstrained plus min rule" "assert unconstrained_scientific_plus_min_payload[\"params\"][\"limit_rule\"] == \"prev_close_0.1pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave decimal plus rule" "assert unconstrained_decimal_plus_payload[\"params\"][\"limit_rule\"] == \"prev_close_12.5pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave min plus rule" "assert constrained_min_plus_payload[\"params\"][\"limit_rule\"] == \"prev_close_0.1pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave scientific notation constrained plus max rule" "assert constrained_scientific_plus_max_payload[\"params\"][\"limit_rule\"] == \"prev_close_30pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "chan backtest limit rule assert" "assert chan_backtest_payload[\"params\"][\"limit_rule\"] == \"prev_close_20pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "wave backtest limit rule assert" "assert wave_backtest_payload[\"params\"][\"limit_rule\"] == \"prev_close_20pct\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "manual timezone invalid offset test" "def test_manual_timezone_trade_dates_reject_single_digit_hour_offsets" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "manual chan +8 invalid sample" "\"trade_date\": \"2026-06-02T09:40:00+8\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "manual wave -5 invalid sample" "\"trade_date\": \"2026-06-02T10:00:00-5\"" "${ROOT_DIR}/backend/tests/test_api.py"
require_pattern "analysis test NaN fallback call" "limit_pct=float(\"nan\")" "${ROOT_DIR}/backend/tests/test_analysis.py"
require_pattern "analysis test inf fallback call" "limit_pct=float(\"inf\")" "${ROOT_DIR}/backend/tests/test_analysis.py"
require_pattern "analysis test -inf fallback call" "limit_pct=float(\"-inf\")" "${ROOT_DIR}/backend/tests/test_analysis.py"
require_pattern "analysis test NaN fallback rule" "assert nan_limit.params[\"limit_rule\"] == \"prev_close_10pct\"" "${ROOT_DIR}/backend/tests/test_analysis.py"
require_pattern "analysis test inf fallback rule" "assert inf_limit.params[\"limit_rule\"] == \"prev_close_10pct\"" "${ROOT_DIR}/backend/tests/test_analysis.py"
require_pattern "analysis test -inf fallback rule" "assert neg_inf_limit.params[\"limit_rule\"] == \"prev_close_10pct\"" "${ROOT_DIR}/backend/tests/test_analysis.py"
require_pattern "api doc mention" "limit_pct" "${ROOT_DIR}/docs/api.md"
require_pattern "rules doc mention" "limit_pct" "${ROOT_DIR}/docs/rules.md"
require_pattern "readme mention" "limit_pct" "${ROOT_DIR}/README.md"
require_pattern "api doc finite-value constraint" "NaN/Infinity" "${ROOT_DIR}/docs/api.md"
require_pattern "api doc scientific notation constraint" "1e1" "${ROOT_DIR}/docs/api.md"
require_pattern "api doc scientific notation upper constraint" "1E1" "${ROOT_DIR}/docs/api.md"
require_pattern "api doc scientific notation plus constraint" "%2B1e1" "${ROOT_DIR}/docs/api.md"
require_pattern "api doc scientific notation plus upper constraint" "%2B1E1" "${ROOT_DIR}/docs/api.md"
require_pattern "rules doc finite-value constraint" "NaN/Infinity" "${ROOT_DIR}/docs/rules.md"
require_pattern "rules doc scientific notation constraint" "1e1" "${ROOT_DIR}/docs/rules.md"
require_pattern "rules doc scientific notation upper constraint" "1E1" "${ROOT_DIR}/docs/rules.md"
require_pattern "rules doc scientific notation plus constraint" "%2B1e1" "${ROOT_DIR}/docs/rules.md"
require_pattern "rules doc scientific notation plus upper constraint" "%2B1E1" "${ROOT_DIR}/docs/rules.md"
require_pattern "readme finite-value constraint" "NaN/Infinity" "${ROOT_DIR}/README.md"
require_pattern "readme scientific notation constraint" "1e1" "${ROOT_DIR}/README.md"
require_pattern "readme scientific notation upper constraint" "1E1" "${ROOT_DIR}/README.md"
require_pattern "readme scientific notation plus constraint" "%2B1e1" "${ROOT_DIR}/README.md"
require_pattern "readme scientific notation plus upper constraint" "%2B1E1" "${ROOT_DIR}/README.md"

echo "[limit-pct-guard] passed"
